### ISSUE TITLE
No output on Circuit Playground Express

### ISSUE THREAD

**Issue by Daedal0s** [adafruit/Adafruit_NeoPXL8#1]
Hello,

I am using a Circuit Playground Express (CPX) for its collection of onboard sensors, but I would also like to drive multiple strands of neopixels with low CPU overhead.  NeoPXL8 seems like the perfect solution, however I cannot seem to get any output from the physical pins when I run the demo Strandtest.ino file.

I have modified the instantiation of the 'leds' object to use the pins available on the CPX (based on my reading from the older NeoPXL8 documentation).

Here is the modified line of code.  All other code is unchanged from the demo.

int8_t LED_Pins[8] = { 0, 1, 2, 3, A3, -1, 6,  -1};	// CPX
Adafruit_NeoPXL8 leds(NUM_LED, LED_Pins, NEO_GRBW);

I did make sure to select the correct board from the boards manager.

Neopixel strips I'm using are RGBW strips, running on their own 4V supplies.  All grounds are tied together.  All strips work fine when driven from other code.

I tried running the Strandtest.ino code on a "Trinket M0", and I was able to get working output from pins D0 and D2.  I don't have a feather M0 or M4 on-hand to try.

Any help greatly appreciated!

**Comment by PaintYourDragon** [comment]
Only a single pin on Circuit Playground Express (A1) is compatible with NeoPXL8. The Adafruit_NeoPixel_ZeroDMA library might be a slightly better choice, on the CPX it works with pins A2 and A7 (it's less of a RAM hog than NeoPXL8, but still a RAM hog, just less so).

**Comment by Daedal0s** [comment]
Thanks for the information, PYD.  I was definitely oversimplifying things.
Per Discord conversation w/ Jaswope, he suggests that the following lines could be added to the declaration of tcc0pinMap to enable two more pin options on CPX.

{ PORTA, 6, 0, PIO_TIMER }, // CPX A2
{ PORTA, 7, 1, PIO_TIMER }, // CPX A3

If I really get stubborn about using the CPX, then I might re-purpose the PB-A and the slide switch on PA14 and PA15.  But that's still only 4 strands, max.  Such a pity.
