### ISSUE TITLE
NeoPXL8 Library on RP2040 does not stop state machine on destruction

### ISSUE THREAD

**Issue by MarcusGarfunkel** [adafruit/Adafruit_NeoPXL8#10]
- Arduino board:  **INSERT ARDUINO BOARD NAME/TYPE HERE**
Raspberry Pi Pico

- Arduino IDE version (found in Arduino -> About Arduino menu):  **INSERT ARDUINO
  VERSION HERE**
Arduino IDE 2.0.4

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): **LIST REPRO STEPS BELOW**
When instantiating a NeoPXL8 object, a pio sm is claimed and started, the sm program is written, and a DMA IRQ handler is added.
Upon destruction, the reverse of this process has been left out.
[MarcusEdit NeoPXL8.zip](https://github.com/adafruit/Adafruit_NeoPXL8/files/11036540/MarcusEdit.NeoPXL8.zip)
See edits to library files for a fix that seems to work for me.

**Comment by MarcusGarfunkel** [comment]
I've created a pull request #11 for this issue.

**Comment by jepler** [comment]
Thanks for the fix!
