### ISSUE TITLE
Support for Raspberry Pi Pico 2 - RP2350

### ISSUE THREAD

**Issue by FeuerSturm** [adafruit/Adafruit_NeoPXL8#13]
Hi,

I'd love to see support for the recently released Raspberry Pi Pico 2 - RP2350.
https://www.raspberrypi.com/products/rp2350/

It features 12 PIO state machines and thus driving 12 pins simultaneously would be possible.

Is this already being worked on?

Thanks!

**Comment by FeuerSturm** [comment]
I've been trying to modify the NeoPXL8 lib myself with my limited knowledge
to test it with my generic Pico 2.

I can get led data to 12 pins now, **BUT** the 9th, 10th, 11th and 12th pin are just duplicating
the led data from 1st, 2nd, 3rd and 4th pin.

I'm pretty sure that I have some logical errors in my edits or edited stuff that shouldn't have been edited.

Just in case someone is bored and would like to take a look at what might be wrong, I'd be greatful for a
helping hand:
https://github.com/FeuerSturm/Adafruit_NeoPXL8

Thanks in advance!

**Comment by jepler** [comment]
The code builds on the Pico 2 but we haven't tested it out on hardware yet.

**Comment by jepler** [comment]
Note that as each NeoPXL8 instance takes 1 PIO state machine to control 8 strands on 8 pins, you may also already be able to control 12 strands using 2 NeoPXL8 instances in your code on the RP2040.
