### ISSUE TITLE
Working with Adafruit Feather M4 Express

### ISSUE THREAD

**Issue by xseignard** [adafruit/Adafruit_NeoPXL8#2]
Hello,
I'm trying to port a previous teensy+w5500 project to feather M4+w5500. (see https://imgur.com/a/bVoNvQq)

I moved the reset pin on the w5500 featherwing to A0, so I freed the pin 10.
Now I'm trying to use the 8 outputs of my 74HC245 but I have some glitches (like flashes on the whole strip).

Here the pins I use:
```
int8_t pins[8] = { 5, 6, 10, 11, 12, -1, -1, -1 };
```
What would be the last 3 I can use ? I tried 13, 0, 1, and 9 but they generates some glitches

Any idea?

PS: I don't use the Adafruit NeoPXL8 FeatherWing

Regards

Xavier

**Comment by xseignard** [comment]
Any update on this?
Regards

**Comment by ladyada** [comment]
no updates - please remove any additional hardware so you're testing *just* the feather m4

**Comment by xseignard** [comment]
Well, the problem stays the same... Still don't know which pins are DMA compatible with the feather m4...

**Comment by PaintYourDragon** [comment]
Do other pins generate glitches for you, or just certain ones?

**Comment by ladyada** [comment]
tested with feather m4, closing due to no reponse
